"""empty message

Revision ID: a853caf0e63d
Revises: 4b1a9445b326
Create Date: 2018-12-26 15:57:27.500579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a853caf0e63d'
down_revision = '4b1a9445b326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('nba_player_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'nba_player_id')
    # ### end Alembic commands ###
